# Generated by Django 5.2.17 on 2026-09-15 13:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
import ztech_sales.core.models.company
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=150)),
                ("job_title", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive users cannot sign in and lose access immediately, including on existing sessions.",
                    ),
                ),
                (
                    "is_system_administrator",
                    models.BooleanField(
                        default=False,
                        help_text="Break-glass flag granting every permission except approval authority, which must be granted through a role.",
                    ),
                ),
                ("must_change_password", models.BooleanField(default=False)),
                (
                    "failed_login_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "db_table": "core_user",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use the three-letter ISO 4217 code."
                            ),
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("symbol", models.CharField(blank=True, max_length=8)),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Number of decimal places amounts are rounded to. OMR uses 3, USD uses 2, JPY uses 0.",
                        validators=[django.core.validators.MaxValueValidator(6)],
                    ),
                ),
                (
                    "rounding_mode",
                    models.CharField(
                        choices=[
                            ("half_up", "Half up"),
                            ("half_even", "Half even (banker's)"),
                        ],
                        default="half_up",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "currencies",
                "db_table": "core_currency",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "code",
                    models.SlugField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use lower-case letters, digits, hyphen and underscore only, starting with a letter or digit.",
                                regex="^[a-z0-9][a-z0-9_-]*$",
                            )
                        ],
                    ),
                ),
                ("legal_name", models.CharField(max_length=200)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Muscat",
                        help_text="IANA time zone of the legal entity. Date-sensitive business rules - notably quotation expiry - are evaluated in this zone, not in the viewer's zone.",
                        max_length=64,
                        validators=[ztech_sales.core.models.company.validate_timezone],
                    ),
                ),
                (
                    "tax_registration_number",
                    models.CharField(blank=True, max_length=40),
                ),
                (
                    "commercial_registration_number",
                    models.CharField(blank=True, max_length=40),
                ),
                ("address_line1", models.CharField(blank=True, max_length=160)),
                ("address_line2", models.CharField(blank=True, max_length=160)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("region", models.CharField(blank=True, max_length=80)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 country code.",
                        max_length=2,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.CharField(blank=True, max_length=200)),
                (
                    "brand_primary_color",
                    models.CharField(
                        default="#1F3A5F",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Use a hex colour such as #1F3A5F."
                            )
                        ],
                    ),
                ),
                (
                    "brand_accent_color",
                    models.CharField(
                        default="#2F7D6E",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Use a hex colour such as #2F7D6E."
                            )
                        ],
                    ),
                ),
                (
                    "logo_path",
                    models.CharField(
                        blank=True,
                        help_text="Path within this client's private storage scope. Never served from a static URL.",
                        max_length=255,
                    ),
                ),
                (
                    "document_footer",
                    models.TextField(
                        blank=True,
                        help_text="Shown at the foot of customer documents. Never include internal notes or approval policy.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="core.currency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "db_table": "core_company",
                "ordering": ["legal_name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "code",
                    models.SlugField(
                        max_length=48,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use lower-case letters, digits, hyphen and underscore only, starting with a letter or digit.",
                                regex="^[a-z0-9][a-z0-9_-]*$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Seeded with the client environment. Its code cannot be changed or deleted.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_role",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "db_table": "core_role_permission",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "granted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_user_role",
                "ordering": ["-granted_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=200)),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="For example quotation.issued.",
                        max_length=64,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="For example sales.quotation.",
                        max_length=64,
                    ),
                ),
                ("entity_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("entity_label", models.CharField(blank=True, max_length=200)),
                ("summary", models.CharField(blank=True, max_length=400)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Field-level before/after values: {"field": {"from": ..., "to": ...}}.',
                    ),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                (
                    "source",
                    models.CharField(
                        default="web",
                        help_text="web, worker, command or integration.",
                        max_length=24,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "core_audit_event",
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["company", "entity_type", "entity_id"],
                        name="idx_audit_entity",
                    ),
                    models.Index(
                        fields=["company", "-occurred_at"], name="idx_audit_recent"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "key",
                    models.SlugField(
                        help_text="For example quotation or sales_order.", max_length=48
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "prefix",
                    models.CharField(
                        blank=True, help_text="For example QT- or SO-.", max_length=16
                    ),
                ),
                ("padding", models.PositiveSmallIntegerField(default=5)),
                ("next_value", models.PositiveIntegerField(default=1)),
                (
                    "reset_period",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("yearly", "Every year"),
                            ("every month", "Every month"),
                        ],
                        default="yearly",
                        max_length=16,
                    ),
                ),
                (
                    "current_period",
                    models.CharField(blank=True, editable=False, max_length=8),
                ),
                ("include_period_in_reference", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_document_sequence",
                "ordering": ["key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "key"), name="uniq_sequence_key_per_company"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=160, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed - will retry"),
                            ("dead", "Failed - retries exhausted"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=8)),
                (
                    "available_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=64)),
                ("last_error", models.TextField(blank=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_messages",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "core_outbox_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "available_at"], name="idx_outbox_due"
                    ),
                    models.Index(
                        fields=["topic", "status"], name="idx_outbox_topic_status"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="uniq_role_code_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "code"), name="uniq_permission_per_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("user", "role"), name="uniq_role_per_user"
            ),
        ),
    ]
